### ISSUE TITLE
Set up gh-pages branch

### ISSUE THREAD

**Issue by baisong** [anomalyjane/TrumpSplain#1]
To-do:

Make it available at:
 - http://anomalyjane.github.io/TrumpSpeak

**Comment by blackwood** [comment]
Make an index.js file too?

**Comment by blackwood** [comment]
👍

**Comment by anomalyjane** [comment]
Ok, since I got some hosting for burro's tail anyway, I decided to just use it for TrumpSplain too ("TrumpSpeak" was already taken by a trump supporter!). I don't know if there's any additional steps I need to take to get the URL hooked up to the hosting, but I think it's set. @blackwood What goes in index.js?
